title: Abigail Silin
description: A work in progress as I'm learning (and re-learning) how to code. Some links below may re-route to my LinkedIn profile.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect

