title: Abigail Silin's Resume
description: A work in progress as I'm learning (and re-learning) how to code
show_downloads: true
google_analytics:
theme: jekyll-theme-merlot

site.github.zip_url
github:
  zip_url: http://aesilin.com/download.zip
  another_url: http://aesilin.com
